# Generated by Django 5.1.4 on 2024-12-11 17:07

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0003_forms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'Answer',
            },
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('choice', models.CharField(max_length=5000)),
                ('is_answer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
                'db_table': 'Choices',
            },
        ),
        migrations.AlterModelOptions(
            name='forms',
            options={'verbose_name': 'Form', 'verbose_name_plural': 'Forms'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='forms',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to='form_builder.user'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='DateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('value', models.DateField()),
                ('specification', models.JSONField(default=dict)),
                ('answer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_date', to='form_builder.answer')),
            ],
            options={
                'verbose_name': 'DateType',
                'verbose_name_plural': 'DateTypes',
                'db_table': 'DateType',
            },
        ),
        migrations.CreateModel(
            name='DropdownType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('specification', models.JSONField(default=dict)),
                ('answer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_dropdown', to='form_builder.answer')),
            ],
            options={
                'verbose_name': 'DropdownType',
                'verbose_name_plural': 'DropdownTypes',
                'db_table': 'DropdownType',
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('value', models.FileField(upload_to='answer_files')),
                ('specification', models.JSONField(default=dict)),
                ('answer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_file', to='form_builder.answer')),
            ],
            options={
                'verbose_name': 'FileType',
                'verbose_name_plural': 'FileTypes',
                'db_table': 'FileType',
            },
        ),
        migrations.CreateModel(
            name='MatrixType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('specification', models.JSONField(default=dict)),
                ('answer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_matrix', to='form_builder.answer')),
            ],
            options={
                'verbose_name': 'MatrixType',
                'verbose_name_plural': 'MatrixType',
                'db_table': 'MatrixType',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('label', models.CharField(max_length=250)),
                ('title', models.TextField()),
                ('order', models.SmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('constraints', models.CharField(choices=[('RQ', 'Required'), ('OP', 'Optional')], default='OP', max_length=2)),
                ('question_type', models.CharField(choices=[('TXT', 'Text'), ('DRP', 'Dropdown'), ('DTP', 'Date Picker'), ('RKG', 'Ranking'), ('LSL', 'Linear Scale'), ('TMP', 'Time Picker'), ('FLU', 'File Upload'), ('MTX', 'Matrix/Grid'), ('IMC', 'Image Choice'), ('SLD', 'Slider'), ('GOL', 'Geo Location'), ('PAL', 'Percentage Allocation'), ('SGC', 'Signature Capture')], default='TXT', max_length=3)),
                ('choices', models.ManyToManyField(related_name='choices', to='form_builder.choices')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'Questions',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to', to='form_builder.questions'),
        ),
        migrations.AddField(
            model_name='forms',
            name='questions',
            field=models.ManyToManyField(blank=True, to='form_builder.questions'),
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('response_code', models.CharField(max_length=20)),
                ('responder_ip', models.CharField(max_length=30)),
                ('responder_email', models.EmailField(blank=True, max_length=254)),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responder', to='form_builder.user')),
                ('response', models.ManyToManyField(related_name='response', to='form_builder.answer')),
                ('response_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_to', to='form_builder.forms')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
                'db_table': 'Response',
            },
        ),
        migrations.CreateModel(
            name='TimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('value', models.TimeField()),
                ('specification', models.JSONField(default=dict)),
                ('answer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_time_type', to='form_builder.answer')),
            ],
            options={
                'verbose_name': 'TimeType',
                'verbose_name_plural': 'TimeTypes',
                'db_table': 'TimeType',
            },
        ),
    ]
