# Generated by Django 5.1.4 on 2024-12-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0004_answer_choices_alter_forms_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='choices',
            field=models.ManyToManyField(blank=True, null=True, related_name='choices', to='form_builder.choices'),
        ),
    ]
