# Generated by Django 5.1.4 on 2024-12-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0005_alter_questions_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('TXT', 'Text'), ('DRP', 'Dropdown'), ('CBX', 'CheckBox'), ('DTP', 'Date Picker'), ('RKG', 'Ranking'), ('LSL', 'Linear Scale'), ('TMP', 'Time Picker'), ('FLU', 'File Upload'), ('MTX', 'Matrix/Grid'), ('IMC', 'Image Choice'), ('SLD', 'Slider'), ('GOL', 'Geo Location'), ('PAL', 'Percentage Allocation'), ('SGC', 'Signature Capture')], default='TXT', max_length=3),
        ),
    ]
