# Generated by Django 5.1.4 on 2024-12-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0006_alter_questions_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
