# Generated by Django 5.1.4 on 2024-12-12 12:30

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0009_alter_responses_responder_alter_forms_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='response_code',
        ),
        migrations.CreateModel(
            name='TextType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('value', models.CharField(max_length=250)),
                ('specification', models.JSONField(default=dict)),
                ('answer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_text', to='form_builder.answer')),
            ],
            options={
                'verbose_name': 'TextType',
                'verbose_name_plural': 'TextTypes',
                'db_table': 'TextType',
            },
        ),
    ]
