# Generated by Django 5.1.4 on 2024-12-12 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0011_rename_response_responses_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
