# Generated by Django 5.1.4 on 2024-12-12 17:07

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0012_answer_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datetype',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='dropdowntype',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='filetype',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='matrixtype',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='timetype',
            name='specification',
        ),
        migrations.AlterField(
            model_name='dropdowntype',
            name='value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='timetype',
            table=None,
        ),
        migrations.CreateModel(
            name='ChoiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('answer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_choice', to='form_builder.answer')),
            ],
            options={
                'verbose_name': 'ChoiceType',
                'verbose_name_plural': 'ChoiceType',
            },
        ),
    ]
